/**
 * Ember responsive initializer
 *
 * Supports auto injecting media service app-wide.
 * Generated by the ember-responsive addon.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function initialize(application: any) {
  application.registerOptionsForType('breakpoints', {
    instantiate: false
  });
}

export default {
  name: 'ember-responsive-breakpoints',
  initialize
};
