/**
 * Ember responsive initializer
 *
 * Supports auto injecting media service app-wide.
 * Generated by the ember-responsive addon.
 */
export function initialize(application) {
  application.registerOptionsForType('breakpoints', { instantiate: false });
  application.inject('controller', 'media', 'service:media');
  application.inject('component', 'media', 'service:media');
  application.inject('route', 'media', 'service:media');
}

export default {
  name: 'responsive',
  initialize
};
